title: Data.gov.sg Data Quality Guide
remote_theme: opengovsg/opendoc-theme
timezone: Asia/Singapore
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
elastic_search:
  index: datagovsg-data-quality-guide
  doctype: bare
section_order:
styling_options:
  primary_brand_color: '#113355'
  logo_path: /assets/logo.png
